### ISSUE TITLE
Erroneous use of PROGMEM modifer.

### ISSUE THREAD

**Issue by rocco8620** [trendmicro/RadioHAL#5]
https://github.com/trendmicro/RadioHAL/blob/50086a92ed84af6a3102d55e7a74fc3900ac2b55/src/RH_RF69.cpp#L8

The modifier PROGMEM in the line should be either dropped or the code that uses the variable `supportedModulationSchemes` should account for the data being stored in FLASH instead of SRAM. 

If not fixed, the code may crash if the compiler happens to put the content of the variable in FLASH instead of SRAM and the code does not expect it.

More info here https://www.arduino.cc/reference/tr/language/variables/utilities/progmem/
and here https://www.esp8266.com/viewtopic.php?f=15&t=11780

**Comment by phretor** [comment]
Pull request #4 fixed this.
